### ISSUE TITLE
Punctuation in account name

### ISSUE THREAD

**Issue by paugusto76** [NikCharlebois/SharePointDSC.Reverse#20]
I have an issue with my service accounts and the script generated.
The service accounts that I use in my dev environments usually have the format <service>.<function> so for SharePoint I end up with accounts like this:

DOMAIN\sp.setup
DOMAIN\sp.farm
DOMAIN\sp.apppool
etc.

The problem is that the script generated by ReverseDSC I have the following lines:

    $Credssp.farm= Get-Credential -UserName "CORP\sp.farm" -Message "Credentials for CORP\sp.farm"
    $Credssp.apppool= Get-Credential -UserName "CORP\sp.apppool" -Message "Credentials for CORP\sp.apppool"
    $Credssp.services= Get-Credential -UserName "CORP\sp.services" -Message "Credentials for CORP\sp.services"

And if I run the script without changing anything it gives an error stating:

PSDesiredStateConfiguration\Configuration : **The property 'farm' cannot be found on this object.** Verify that the
property exists and can be set.

I would suggest to change the way the the $Cred variable name with the account name and replace any problematic characters (Powershell loves punctuation :) ).

**Comment by NikCharlebois** [comment]
@paugusto76 good catch. We had code to handle '-' in the user names, but not '.'. The fix has been included in my dev branch and will make it down to version 1.7.0.0 which I plan on releasing along with the same version of the Forward SharePointDSC in a few days.

**Comment by paugusto76** [comment]
Glad I could help :)
