### ISSUE TITLE
Opening output .ps1 file in Visual Studio 2017 causes prompt about "inconsistent line endings"

### ISSUE THREAD

**Issue by brianlala** [NikCharlebois/SharePointDSC.Reverse#47]
Opening output .ps1 file (generated by v. 1.6.0.7) in Visual Studio 2017 (+ perhaps other versions) causes prompt about "inconsistent line endings". See attached.

Brian

![lineendingserror](https://cloud.githubusercontent.com/assets/12145177/26216132/fb16f9b8-3bd0-11e7-8f3f-61dd22278ab8.png)

**Comment by NikCharlebois** [comment]
This is related to the output of the SQL version which the script doesn't control. Currently investigating if there is a way to trap these invalid \r\n and replace them with the proper encoding.

**Comment by NikCharlebois** [comment]
Fixed in Branch 1.7.0.0. I am now catching the SQL query return and splitting by the invalid line end "\n"
