### ISSUE TITLE
Unhandled exception for 'Custom' Enterprise Search Content Sources

### ISSUE THREAD

**Issue by johndpalm** [NikCharlebois/SharePointDSC.Reverse#57]
Running:

> .\SharePointDSC.Reverse.ps1 -SkipFeatures -SkipWebs -SkipPackageCheck -SkipHealthRules -SkipSearchFileType -SkipTimerJobState

The script crashes with the following error:

> VERBOSE: Leaving BeginProcessing Method of Get-SPEnterpriseSearchCrawlContentSource.
> VERBOSE: Leaving ProcessRecord Method of Get-SPEnterpriseSearchCrawlContentSource.
> VERBOSE: Leaving EndProcessing Method of Get-SPEnterpriseSearchCrawlContentSource.
> SharePointDsc does not currently support 'Custom' content sources. Please use only 'SharePoint', 'FileShare' or 'Website'.
> At line:114 char:17
> + ...             throw ("SharePointDsc does not currently support '$($sour ...
> +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : OperationStopped: (SharePointDsc d...' or 'Website'.:String) [], RuntimeException
>     + FullyQualifiedErrorId : SharePointDsc does not currently support 'Custom' content sources. Please use only 'SharePoint', 'FileShare' or 'Website'.

Is there some way to identify that it is using a custom source, or skip it, without crashing the scan?  Or a skip switch for the content sources?

ReverseDSC 1.7.1.1
SharePointDSC 1.7.0.0
PSVersion 5.0.10586.117
Windows Server 2012 R2

**Comment by NikCharlebois** [comment]
Hi John, this is a limitation of the SharePointDSC module. As you suggested, we will modify the Reverse script to filter out Custom content sources and let it continue its normal execution. Thanks

**Comment by NikCharlebois** [comment]
Fixed in the new 1.8.0.0 Release
