### ISSUE TITLE
SPWebAppPolicy is not included

### ISSUE THREAD

**Issue by shurick81** [NikCharlebois/SharePointDSC.Reverse#6]
This project is really great! One issue though: I have analyzed my dev farm with this tool and it seems that SPWebAppPolicy is not included in generated configuration.

**Comment by NikCharlebois** [comment]
I just never got around setting up the CIMInstance array that would be required for that. I will kepp it on my radar for future releases

**Comment by NikCharlebois** [comment]
@shurick81 Included in upcoming release 1.7.0.0
